sudo: false

dist: trusty

language: cpp

compiler:
    - gcc
    - clang
env:
    matrix:
        - CMAKE_BUILD_TYPE=Release
        - CMAKE_BUILD_TYPE=Debug 

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - gcc-5
    - g++-5
    - clang-3.8

before_script:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
- uname -a
- printenv
- clang++ --version 2>&1 | grep clang
- g++ --version 2>&1 | grep g++

script:
- cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE .
- make
- ctest --output-on-failure

notifications:
  email:
    recipients:
    - martinjrobins@gmail.com
